### ISSUE TITLE
codm cn version can't dump

### ISSUE THREAD

**Issue by JacksonTai2007** [Poko-Apps/Il2CppDumperCODM#3]
Initializing metadata...
Metadata Version: 23
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 23
Searching...
CodeRegistration : c0fb968
MetadataRegistration : c0fba10
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration)
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\Users\Poko\Desktop\Codm_1047\Il2CppDumper\Il2CppDumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 114
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\Users\Poko\Desktop\Codm_1047\Il2CppDumper\Il2CppDumper\Il2CppDumper\ExecutableFormats\Elf64.cs:line 97
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\Users\Poko\Desktop\Codm_1047\Il2CppDumper\Il2CppDumper\Il2CppDumper\Program.cs:line 121
ERROR: An error occurred while processing.
Press any key to exit...

**Comment by JacksonTai2007** [comment]
Sorry, now I know how to dump, but I have a question,how to get the il2cpp binary from game's memory at runtime in iOS?

**Comment by JacksonTai2007** [comment]
now all done
